copyrights The copyright norices have been changed to remove the "all rights reserved" phrase.  It did not represent the GPL spirit.

diff --git a/etc/template/test b/etc/template/test
--- a/etc/template/test
+++ b/etc/template/test
@@ -1,22 +1,21 @@
 #!/bin/sh
 #
-#	srecord - manipulate eprom load files
-#	Copyright (C) ${date %Y} Peter Miller;
-#	All rights reserved.
+#       ${project trunk_name} - ${project trunk_description}
+#       Copyright (C) ${date %Y} ${copyright_owner}
 #
-#	This program is free software; you can redistribute it and/or modify
-#	it under the terms of the GNU General Public License as published by
-#	the Free Software Foundation; either version 2 of the License, or
-#	(at your option) any later version.
+#       This program is free software; you can redistribute it and/or modify
+#       it under the terms of the GNU General Public License as published by
+#       the Free Software Foundation; either version 2 of the License, or
+#       (at your option) any later version.
 #
-#	This program is distributed in the hope that it will be useful,
-#	but WITHOUT ANY WARRANTY; without even the implied warranty of
-#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#	GNU General Public License for more details.
+#       This program is distributed in the hope that it will be useful,
+#       but WITHOUT ANY WARRANTY; without even the implied warranty of
+#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#       GNU General Public License for more details.
 #
-#	You should have received a copy of the GNU General Public License
-#	along with this program; if not, write to the Free Software
-#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
+#       You should have received a copy of the GNU General Public License
+#       along with this program; if not, write to the Free Software
+#       Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
 #
 # MANIFEST: Test the ??? functionality
 #
@@ -26,26 +25,26 @@ work=$${TMP_DIR-/tmp}/$$$$
 
 pass()
 {
-	cd $$here
-	rm -rf $$work
-	echo PASSED
-	exit 0
+        cd $$here
+        rm -rf $$work
+        echo PASSED
+        exit 0
 }
 
 fail()
 {
-	cd $$here
-	rm -rf $$work
-	echo 'FAILED test of the ??? functionality'
-	exit 1
+        cd $$here
+        rm -rf $$work
+        echo 'FAILED test of the ??? functionality'
+        exit 1
 }
 
 no_result()
 {
-	cd $$here
-	rm -rf $$work
-	echo 'NO RESULT for test of the ??? functionality'
-	exit 2
+        cd $$here
+        rm -rf $$work
+        echo 'NO RESULT for test of the ??? functionality'
+        exit 2
 }
 
 trap "no_result" 1 2 3 15
@@ -83,3 +82,5 @@ if test $$? -ne 0; then fail; fi
 # No other guarantees are made.
 #
 pass
+
+# vim:ts=8:sw=4:et
